experiment:
  name: "bc_optimization"
  seed: 16
  n_optuna_trials: 20
  max_epochs_phase_1: 150
  max_epochs_phase_2: 250
  # large batch sizes for faster tuning, dataset is large shoudnt be a problem for phase 1
  batch_size_phase_1: 512
  # smaller batch sizes for more precise training
  batch_size_phase_2: 512
  early_stopping_criterion_epochs: 5
  stratified_train_set_ratio: 0.6

search_space:
  dropout:
    type: "float"
    low: 0.0
    high: 0.3
    step: 0.05

  lr:
    type: "float"
    low: 1e-4
    high: 1e-3
    log: true

  num_hidden_neurons:
    type: "int"
    low: 32
    high: 128
    step: 32

  num_hidden_layers:
    type: "int"
    low: 1
    high: 6

  weight_decay:
    type: "float"
    low: 1e-5
    high: 1e-4
    log: true

runtime:
  device: "cuda"
  best_model_dir: "../models/BC"
  log_dir: "../logs/BC_training"
